FROM ghcr.io/blinklabs-io/go:1.26.7-1 AS build
WORKDIR /code
RUN go env -w GOCACHE=/go-cache && go env -w GOMODCACHE=/gomod-cache
COPY go.* ./
RUN --mount=type=cache,target=/gomod-cache go mod download
COPY . .
RUN --mount=type=cache,target=/gomod-cache --mount=type=cache,target=/go-cache \
    go build -tags antithesis -o /code/analysis ./cmd/analysis/

FROM debian:bookworm-slim
RUN apt-get update -y && \
    apt-get install -y --no-install-recommends ca-certificates && \
    rm -rf /var/lib/apt/lists/*
RUN useradd --uid 1000 -m analysis
COPY --from=build /code/analysis /bin/analysis
USER analysis
ENTRYPOINT ["/bin/analysis"]
