global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: cardano-node
    metrics_path: /metrics
    static_configs:
      - targets: ["cardano-node:12798"]

  - job_name: bursa
    metrics_path: /metrics
    static_configs:
      - targets: ["bursa:8081"]
